version: '3.9'

services:
  konga:
    image: pantsel/konga:latest
    container_name: my-konga
    depends_on: 
      kong:
        condition: service_healthy
    ports:
      - 1337:1337
    networks:
      - kong-net
    env_file:
      - .envs/konga
    volumes:
      - type: bind
        source: "./konga"
        target: "/konga-config"
    restart: on-failure

  kong-migrations:
    image: kong:2.8
    container_name: my-kong-migration
    command: kong migrations bootstrap
    env_file:
      - .envs/kong
    depends_on:
      - db
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
      - ./config:/opt/kong
      - type: bind
        source: "./plugins/01-my-plugin"
        target: "/usr/local/share/lua/5.1/kong/plugins/01-my-plugin"
    networks:
      - kong-net
    restart: on-failure

  kong-migrations-up:
    image: kong:2.8
    container_name: my-kong-migration-up
    command: kong migrations up && kong migrations finish
    env_file:
      - .envs/kong
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
      - ./config:/opt/kong
      - type: bind
        source: "./plugins/01-my-plugin"
        target: "/usr/local/share/lua/5.1/kong/plugins/01-my-plugin"
    networks:
      - kong-net
    restart: on-failure

  kong:
    platform: linux/arm64
    image: kong:2.8
    container_name: my-kong
    user: kong
    env_file:
      - .envs/kong
    depends_on:
      kong-migrations-up:
        condition: service_completed_successfully
    networks:
      - kong-net
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
      - ./config:/opt/kong
      - type: bind
        source: "./plugins/01-my-plugin"
        target: "/usr/local/share/lua/5.1/kong/plugins/01-my-plugin"
    security_opt:
      - no-new-privileges

  db:
    image: postgres:9.5
    container_name: my-postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    env_file:
      - .envs/postgres
    tty: true
    ports:
      - 5432:5432
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

  echoserver:
    image: ealen/echo-server:latest
    container_name: my-echoserver
    logging:
      driver: none
    networks:
      - kong-net
    depends_on:
      kong:
        condition: service_healthy

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
     type: tmpfs
     device: tmpfs
  kong_tmp_vol:
    driver_opts:
     type: tmpfs
     device: tmpfs

networks:
  kong-net:
    external: false


